#! /usr/bin/python

import sys
import codecs

def main(argv):
	output = ""
	for section in argv:
		output += (codecs.encode(section, 'rot_13') + " ")
	print output

def piping():
	for line in sys.stdin:
	#	print codecs.encode(line, 'rot_13')
		sys.stdout.write(codecs.encode(line, 'rot_13'))


if __name__ == '__main__':
	if not sys.stdin.isatty():
		piping()
	else:
		main(sys.argv[1:])